### ISSUE TITLE
error in combine_spectra.py when dealing with low S/N data

### ISSUE THREAD

**Issue by aburgasser** [pyspextool/pyspextool#111]
found a recurring, fatal issue when dealing with low (but still visibly extractable) S/N data in combine_array.py where "scale_array" is producing negative numbers:

/Users/adam/python_codes/pyspextool/src/pyspextool/combine/combine_spectra.py:805: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(scale_array),
Traceback (most recent call last):
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 227, in <module>
    app = runBatch()
  File "/Users/adam/python_codes/pyspextool/batch_cl.py", line 197, in __init__
    batch.batchReduce(par,verbose=(not args['quiet']))
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/batch/batch.py", line 1487, in batchReduce
    ps.combine.combine_spectra(['spectra',spar['TARGET_FILES']],'{}{}'.format(spar['COMBINED_FILE_PREFIX'],fsuf),
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/combine/combine_spectra.py", line 304, in combine_spectra
    plot_allorders(file_info=qafileinfo, suffix='_scaled',
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/combine/combine_spectra.py", line 619, in plot_allorders
    uncertainty_ranges[i,:] = get_stack_range(uncertainty[0,i], savgol=True,
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/plot/limits.py", line 202, in get_stack_range
    result = robust_savgol(x_values, stack[i,:], savgol_window)
  File "/Users/adam/python_codes/pyspextool/src/pyspextool/fit/robust_savgol.py", line 80, in robust_savgol
    newyy = scipy.signal.savgol_filter(yy, window_length, polyorder)
  File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/scipy/signal/_savitzky_golay.py", line 345, in savgol_filter
    raise ValueError("If mode is 'interp', window_length must be less "
ValueError: If mode is 'interp', window_length must be less than or equal to the size of x.

I printed out the scale_array values for this case and they were as follows:

[[ 1.0022696   1.0022696   1.0022696  ...  1.0022696   1.0022696
   1.0022696 ]
 [-0.91867143 -0.91867143 -0.91867143 ... -0.91867143 -0.91867143
  -0.91867143]
 [ 0.99774066  0.99774066  0.99774066 ...  0.99774066  0.99774066
   0.99774066]
 [ 0.4042165   0.4042165   0.4042165  ...  0.4042165   0.4042165
   0.4042165 ]]

clearly the second file is problematic. 

simple fix is to add line at 798:
scale_array = np.absolute(scale_array)

but want to check if that is as intended

The relevant dataset is here: https://drive.google.com/file/d/1GqLa37-DphnpNhmT1d4xfqT-WPS-kOhs/view?usp=drive_link

files:
source: 2035-2038
calibrations: 2063-2068
standard: 2055-2062

**Comment by michaelcushing** [comment]
Let me look into it as I am not sure taking the absolute value is the right thing to do.

**Comment by aburgasser** [comment]
I think the fix might have already been in the code when you ran it?

but yes, this is the line, although I'm not setting the statistic - is mean default?

**Comment by michaelcushing** [comment]
I commented out the absolute and and it still ran ok.  Perhaps you can send me the spectra files on which it is breaking?

**Comment by aburgasser** [comment]
individual spectra files are here: https://drive.google.com/drive/folders/1yyeJmXipReid1IfRMf3xF-6dFZMyyFQb?usp=sharing
