### ISSUE TITLE
Something wrong with the I/O of my files

### ISSUE THREAD

**Issue by ctheissen** [pyspextool/pyspextool#135]
I have a night of SXD data and a couple of the objects throw the following warning.

```
Traceback (most recent call last):
  File "/Users/ctheissen/repos/pyspextool/batch_cl.py", line 228, in <module>
    app = runBatch()
  File "/Users/ctheissen/repos/pyspextool/batch_cl.py", line 198, in __init__
    batch.batchReduce(par,verbose=(not args['quiet']))
  File "/Users/ctheissen/repos/pyspextool/src/pyspextool/batch/batch.py", line 1428, in batchReduce
    ps.extract.load_image([spar['TARGET_PREFIX'],extract_filestring(spar['TARGET_FILES'],'index')[:2]],\
  File "/Users/ctheissen/repos/pyspextool/src/pyspextool/io/files.py", line 78, in extract_filestring
    oarr.append(int(lowupp[0]))
```

It seems like there is something wrong with the filenames? Or maybe something in the header? Here are the relevant files (flats, arc, science, standard).
https://drive.google.com/file/d/1KXvlTgJitrcSczlLgdSayZYCn3U0Lza4/view?usp=sharing

**Comment by ctheissen** [comment]
@michaelcushing were you able to reduce this object not using batch mode?

**Comment by michaelcushing** [comment]
Misinterpreted.   Thought the data was the entire night.  Will take a look but trying to check off older bugs first.

**Comment by michaelcushing** [comment]
I was able to reduce the data from the command line so it looks like it might be something with the bath program.  @aburgasser
